name: 'Build & Publish with Moka'
description: 'Clones the child repo and Moka engine, copies assets, builds, and publishes to GitHub Pages.'
icon: 'book-open'
color: 'yellow'
inputs:
  github_token:
    description: 'GitHub Token for publishing'
    required: true
  moka_repo:
    description: 'Repository of the Moka engine'
    default: 'fiches-me/moka'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout Moka Engine
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.moka_repo }}
        path: 'moka-engine'

    - name: Checkout Child Repo
      uses: actions/checkout@v4
      with:
        path: 'moka-engine/content/docs'

    - name: 'Setup Node'
      uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: Install Dependencies
      shell: bash
      run: |
        cd moka-engine
        npm install

    - name: Copy & Clean Assets
      shell: bash
      run: |
        # Copy logo from child repo to moka engine
        if [ -f "moka-engine/content/docs/.moka/logo.ico" ]; then
          echo "Copying logo from moka-engine/content/docs/.moka/logo.ico to moka-engine/public/favicon.png"
          cp moka-engine/content/docs/.moka/logo.ico moka-engine/public/favicon.ico
        else
          echo "No logo found at moka-engine/content/docs/.moka/logo.ico, skipping."
        fi
        if [ -f "moka-engine/content/docs/README.md" ]; then
          echo "Removing file from moka-engine/content/docs/README.md"
          rm moka-engine/content/docs/README.md
        else
          echo "No file found at moka-engine/content/docs/README.md, skipping."
        fi

        recurseMDtoMDX() {
          for file in "$1"/*; do
            if [ -d "$file" ]; then
              recurseMDtoMDX "$file"
            else
              if [[ $file == *.md ]]; then
                mv "$file" "${file%.*}.mdx"
              fi
            fi
          done
        }

        recurseMDtoMDX "moka-engine/content/docs"


    - name: Build Moka
      shell: bash
      run: |
        cd moka-engine
        npm run build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: moka-engine/build/client
